name: Deploy Microservice Paiement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
        echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
        echo "STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}" >> .env
        echo "PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}" >> .env
        echo "PAYPAL_CLIENT_SECRET=${{ secrets.PAYPAL_CLIENT_SECRET }}" >> .env
        echo "PAYPAL_MODE=${{ secrets.PAYPAL_MODE}}" >> .env
        
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: nrajaona/kimaiko:payment-${{ github.sha }}
        file: ./Dockerfile
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_CLIENT_SECRET=${{ secrets.PAYPAL_CLIENT_SECRET }}
          PAYPAL_MODE=${{ secrets.PAYPAL_MODE }}
          BASE_URL=${{ secrets.BASE_URL }}

    - name: Update Docker Image Tag in Deployement File
      run: |
        sed -i "s#nrajaona/kimaiko:payment#nrajaona/kimaiko:payment-${{ github.sha }}#" docker-compose.yaml
    
    - name: Copy All Deployment File
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "docker-compose.yaml"
        target: "/home/debian/ms_payment"

    - name: Deploy MS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          echo "Deploy Microservice..."
          chmod +x /home/debian/ms_payment/payment.sh
          /home/debian/ms_payment/payment.sh